# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_level',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionLevel',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
