# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_charities_storecharityhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accepts_marketing_emails',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accepts_status_emails',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='terms_and_conditions_consent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='round_up_product_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storecharityhistory',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_charity', to=settings.AUTH_USER_MODEL),
        ),
    ]
