# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180108_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
