# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180110_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shop_owner_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shop_owner_last_name',
        ),
    ]
