# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 17:08
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rounduporders'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounduporders',
            name='shopify_created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 8, 42, 398000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
