# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_stripetransfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransfers',
            name='destination_charity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_app.Charities'),
            preserve_default=False,
        ),
    ]
